app:
  scheduler:
    enable: true
    interval: PT10S
    force-check-delay: PT10S

bot:
  api:
    baseurl: http://localhost:8090

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

github:
  base:
    url: ${GITHUB_BASE_URL:https://api.github.com}

stackoverflow:
  base:
    url: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com/2.2}

springdoc:
  swagger-ui:
    path: /swagger-ui

rate-limiting:
  capacity: 20
  tokens: 20
  refill-duration: 60
