app:
  scheduler:
    enable: true
    interval: PT10S
    force-check-delay: PT10S


spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

github:
  base:
    url: ${GITHUB_BASE_URL:https://api.github.com}

stackoverflow:
  base:
    url: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com/2.2}

springdoc:
  swagger-ui:
    path: /swagger-ui

