app:
  telegram-token: "${TELEGRAM_TOKEN:unset}"

scrapper:
  api:
    baseurl: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      topic: ${SCRAPPER_UPDATE_TOPIC:update-topic}
      group-id: ${SCRAPPER_GROUP_ID:update-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

rate-limiting:
  capacity: 20
  tokens: 20
  refill-duration: 60 # Время в секундах

backoff:
  strategy: exponential # Или "constant", "linear"
  initialDelay: 1000
  multiplier: 2.0
  increment: 1000
  maxAttempts: 1000
  retryable-status-codes: [500, 502, 503, 504]
